---
- name: Deleting files and folder at remote
  hosts: all

  tasks:
  - name: Creating folder
    file:
      path: /home/admin1/testing
      state: absent

  - name: Creating the file
    file:
      path: /home/admin1/testing/demo.txt
      state: absent
